# Generated by Django 2.0.7 on 2018-07-31 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en', models.CharField(max_length=50, verbose_name='Название категории (англ.)')),
                ('ru', models.CharField(max_length=50, verbose_name='Название категории (рус.)')),
                ('pl', models.CharField(max_length=50, verbose_name='Название категории (польск.)')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=1000, verbose_name='Ссылка на фото')),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.Category', verbose_name='Категория')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
