# Generated by Django 2.0.6 on 2018-07-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_auto_20180625_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='small',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Фото'),
        ),
    ]
