# Generated by Django 2.0.7 on 2018-07-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_auto_20180705_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='small',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Миниатюра'),
        ),
    ]
