# Generated by Django 2.0.7 on 2018-07-30 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0005_auto_20180726_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.CharField(max_length=1000, verbose_name='Ссылка на фото'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='small',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Ссылка на миниатюру'),
        ),
    ]
