# Generated by Django 2.0.7 on 2018-07-30 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0006_auto_20180730_0734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='small',
        ),
    ]
